- app/localizationServer/conf/localizationServer.ini
- app/robotGotoExample/conf/localizationServer.ini
- app/robotPathPlannerExample/conf/localizationServer.ini
- src/localizationServer/CMakeLists.txt
- src/localizationServer/main.cpp
- src/robotPathPlanner/CMakeLists.txt
- src/robotPathPlanner/pathPlanner.cpp
- src/ros_messages/nav_msgs/MapMetaData.msg
- src/ros_messages/nav_msgs/OccupancyGrid.msg
localizationServer can now ask a map to yarp mapServer and publish it as ros OccupancyGrid when initialPosition is updated (only if proper options are set in localizationServer.ini
> Localization server with map

- src/follower/src/FollowerModule.cpp
- src/follower/src/FollowerModule.h
Add messages for monitoring (for CARVE project)
> Follower monitoring

- src/follower/CMakeLists.txt
- src/rosNavigator/CMakeLists.txt
- src/t265Localizer/CMakeLists.txt
- realsense sdk not mandatory
- fix compilation of follower if YARP_BT_module is not found
- removed noise cmake messages
> Fix CMakeFiles

- CMakeLists.txt
- src/baseControl/cer/cer_odometry.cpp
- src/baseControl/cer/cer_odometry.h
- src/baseControl/controlThread.cpp
- src/baseControl/controlThread.h
- src/baseControl/ikart/ikart_odometry.cpp
- src/baseControl/ikart/ikart_odometry.h
- src/baseControl/main.cpp
- src/baseControl/odometryHandler.cpp
- src/baseControl/odometryHandler.h
- src/localizationDevices/odomLocalizer/odomLocalizer.cpp
- src/localizationDevices/odomLocalizer/odomLocalizer.h
- src/localizationDevices/t265Localizer/t265Localizer.cpp
- src/localizationDevices/t265Localizer/t265Localizer.h
* Refactoring due to changes introduced by https://github.com/robotology/yarp/pull/2185
* Added odometry handler in T265Localizer
> Odometry for T265

- src/localizationDevices/amclLocalizer/CMakeLists.txt
- src/localizationDevices/amclLocalizer/amclLocalizer.cpp
- src/localizationDevices/amclLocalizer/amclLocalizer.h
- src/localizationDevices/rosLocalizer/CMakeLists.txt
- src/localizationDevices/rosLocalizer/rosLocalizer.cpp
- src/localizationDevices/rosLocalizer/rosLocalizer.h
- src/localizationDevices/t265Localizer/localizationServer_pb_on_ros_camera3.ini
- src/localizationDevices/t265Localizer/t265Localizer.cpp
- src/localizationDevices/t265Localizer/t265Localizer.h
the following devices have been modified:
* amclLocalizer: added odometry estimation
* rosLocalizer: added odometry estimation
* t265Localizer: added client to manage TF. Fixed reference frames.
> Amcl2 partial

- src/CMakeLists.txt
- src/baseControl/input.cpp
- src/baseControl/input.h
- src/portmonitors/CMakeLists.txt
- src/portmonitors/joystick2velocityCommand/CMakeLists.txt
- src/portmonitors/joystick2velocityCommand/joystick2velocityCommand.cpp
- src/portmonitors/joystick2velocityCommand/joystick2velocityCommand.h
* added joystick2velocityCommand portmonitor
* aux port of basecontrol modified to receive only dataype MobileBaseVelocity. This is a breaking change!
> Joystick bottle -> Velocity Command refactoring

- .travis.yml
- CMakeLists.txt
- src/navigationDevices/rosNavigator/rosNavigator.cpp
> Travis fix

- app/CMakeLists.txt
- app/freeFloorViewer/CMakeLists.txt
- app/freeFloorViewer/conf/freeFloorViewer_sim.ini
- app/freeFloorViewer/conf/gazeboLocalizer.ini
- app/freeFloorViewer/conf/robotGoto_sim_cer.ini
- app/freeFloorViewer/conf/robotPathPlanner_sim_cer.ini
- app/freeFloorViewer/scripts/freeFloorViewer.xml
- src/CMakeLists.txt
- src/freeFloorViewer/CMakeLists.txt
- src/freeFloorViewer/freeFloorThread.cpp
- src/freeFloorViewer/freeFloorThread.h
- src/freeFloorViewer/freeFloorViewer.cpp
- src/freeFloorViewer/freeFloorViewer.h
- src/freeFloorViewer/main.cpp
* Added a new application that allows to detect the obstacle free floor from the RGBD camera depth image and to highlight it on an RGB image in an augmented reality fashion. The application also allows a user to select the point to move the robot to by clicking on it on a yarpview dialog.
> Free floor mask

- src/extendedRangefinder2DWrapper/extendedRangefinder2DWrapper.cpp
- src/extendedRangefinder2DWrapper/extendedRangefinder2DWrapper.h
extendedRangefinder2DWrapper fixed to use yarp::dev::LaserScan2D datatype
> extendedRangefinder2DWrapper fix

- app/freeFloorViewer/conf/freeFloorViewer_cer02.ini
- app/freeFloorViewer/conf/freeFloorViewer_sim.ini
- app/freeFloorViewer/conf/odomLocalizer_cer02.ini
- app/freeFloorViewer/conf/robotGoto_cer02.ini
- app/freeFloorViewer/conf/robotPathPlanner_cer02.ini
- app/freeFloorViewer/scripts/freeFloorViewer_cer02.xml
- src/freeFloorViewer/freeFloorThread.cpp
- src/freeFloorViewer/freeFloorThread.h
- src/freeFloorViewer/freeFloorViewer.cpp
- src/freeFloorViewer/freeFloorViewer.h
Code refactoring for `freeFloorViewer.h`, `freeFloorViewer.cpp`, `freeFloorThread.h`, and `freeFloorThread.cpp`.
Slight modifications to existing `*.ini` files and new ones for the `freeFloorViewer` yarpmanager application.
> refactor_freeFloorViewer: Code refactoring

- app/robotPathPlannerExamples/conf/robotGoto_robot_2wheels_with_recovery.ini
- app/robotPathPlannerExamples/conf/robotPathPlanner_robot_2wheels_with_recovery.ini
- src/common/CMakeLists.txt
- src/common/recovery_behaviors/recovery_behaviors.cpp
- src/common/recovery_behaviors/recovery_behaviors.h
- src/common/recovery_behaviors/stuck_detection.cpp
- src/common/recovery_behaviors/stuck_detection.h
- src/navigationDevices/robotGotoDevice/obstacles.cpp
- src/navigationDevices/robotGotoDevice/obstacles.h
- src/navigationDevices/robotGotoDevice/robotGotoCtrl.cpp
- src/navigationDevices/robotPathPlannerDevice/map.cpp
- src/navigationDevices/robotPathPlannerDevice/pathPlannerCtrl.cpp
- src/navigationDevices/robotPathPlannerDevice/pathPlannerCtrl.h
- src/navigationDevices/robotPathPlannerDevice/pathPlannerCtrlActions.cpp
- src/navigationDevices/robotPathPlannerDevice/robotPathPlannerDev.cpp
- src/navigationDevices/robotPathPlannerDevice/robotPathPlannerDev.h
robotPathPlanner is now able to recompute a new path if robotGoto is stuck
> Stuck detection

- src/CMakeLists.txt
- src/localizationDevices/gazeboLocalizer/CMakeLists.txt
- src/portmonitors/joystick2velocityCommand/CMakeLists.txt
Some plugins were not correctly compiled and the .so was missing of some symbols
> fixed plugins

- src/navigationDevices/rosNavigator/rosNavigator.cpp
- src/navigationDevices/rosNavigator/rosNavigator.h
Integrated Global and Local waypoint from ROS to YARP
> Ros navigator waypoint implementation

- src/baseControl/cer/cer_odometry.cpp
- src/baseControl/controlThread.cpp
- src/baseControl/controlThread.h
- src/baseControl/ikart/ikart_odometry.cpp
- src/baseControl/odometryBroadcaster.cpp
- src/baseControl/odometryBroadcaster.h
- src/baseControl/odometryHandler.cpp
- src/localizationDevices/rosLocalizer/rosLocalizer.cpp
* Added OdometryBroadcaster class
* OdometryHandler class refactored to have streaming output separated from the logic
> BaseControl Odometry Refactor

- src/localizationDevices/rosLocalizer/rosLocalizer.cpp
- src/localizationDevices/rosLocalizer/rosLocalizer.h
Added subscriber to receive localization data directly from a ros topic, without using a transform server. @DatSpace
> Ros localizer rostopic

- src/localizationDevices/ros2Localizer/ros2Localizer.cpp
fixed localization without yarp tf, now it is not opening the frametransform nwc
> fixed bug in ros2 localizer

- app/freeFloorViewer/conf/freeFloorViewer_R1SN003_ROS2.ini
- app/freeFloorViewer/scripts/freeFloorViewer_R1SN003_ROS2.xml
- app/freeFloorViewer/scripts/freeFloorViewer_complete_R1SN003_ROS2.xml
- app/freeFloorViewer/scripts/webTeleopCompleteR1SN003_ROS2.xml
New set of `.xml` files and `.ini` files to use `freeFloorViewer` with ROS2 on `R1SN003`
> Feature: freeFloorViewer ROS2 xml robot

- src/navigationGUI/map.cpp
- src/navigationGUI/navGui.cpp
Removed also some trailing white spaces
> Replaced getIplImage with getRawImage

- src/follower/src/ObstacleAvoidance.cpp
- src/follower/src/ObstacleAvoidance.h
- src/localizationDevices/amclLocalizer/amclLocalizer.h
- src/navigationDevices/robotGotoDevice/obstacles.cpp
- src/navigationDevices/robotGotoDevice/obstacles.h
- src/navigationDevices/robotGotoDevice/robotGotoCtrl.h
- src/navigationDevices/robotPathPlannerDevice/pathPlannerCtrl.cpp
- src/navigationGUI/navGui.cpp
A set of outdated include have been fixed in order to be compatible with `yarp::master`
> Fixes fo yarp master compatibility

- src/navigationDevices/ros2Navigator/ros2Navigator.cpp
Now the repo compiles with ros2 kilted.
> Added fix to allow the repo compilation with ros2 kilted
